createSubscriber:
  handler: gatways/subscriber/main.createSubscriber
  events:
    - http:
        path: /subscriber/create
        method: post
        cors: true
        private: true
deleteSubscriber:
  handler: gatways/subscriber/main.delete
  events:
    - http:
        path: /subscriber
        method: delete
        cors: true
        private: true
countSubscribers:
  handler: gatways/subscriber/main.countSubscribers
  events:
    - http:
        path: /subscriber/count
        method: get
        cors: true
        private: true
updateSubscriber:
  handler: gatways/subscriber/main.update
  events:
    - http:
        path: /subscriber/update
        method: put
        cors: true
        private: true

findSubscriberByDocument:
  handler: gatways/subscriber/main.findByDocument
  events:
    - http:
        path: /subscriber/find
        method: get
        cors: true
        private: true

updatePassword:
  handler: gatways/subscriber/main.updatePassword
  events:
    - http:
        path: /subscriber/updatepassword/document/{document}
        method: post
        cors: true
        private: true
        request:
        parameters:
          paths:
            document: true
loginSubscriber:
  handler: gatways/subscriber/main.login
  events:
    - http:
        path: /subscriber/login
        method: post
        cors: true
        private: true

forgotPassword:
  handler: gatways/subscriber/main.forgotPassword
  events:
    - http:
        path: /subscriber/forgotpassword/document/{document}
        method: get
        cors: true
        private: true
        request:
        parameters:
          paths:
            document: true
linkBillingCard:
  handler: gatways/subscriber/main.linkBillingCard
  events:
    - http:
        path: /subscriber/card
        method: post
        cors: true
        private: true
deleteBillingCard:
  handler: gatways/subscriber/main.deleteCardByCustomer
  events:
    - http:
        path: /subscriber/card/{cardId}
        method: delete
        cors: true
        private: true
        parameters:
          paths:
            cardId: true
paymentSignature:
  handler: gatways/subscriber/main.paymentAssignature
  events:
    - http:
        path: /subscriber/signature
        method: post
        cors: true
        private: true
getSignature:
  handler: gatways/subscriber/main.getSignature
  events:
    - http:
        path: /signature
        method: get
        cors: true
        private: true
cancelSignature:
  handler: gatways/subscriber/main.cancelSignature
  events:
    - http:
        path: /subscriber/signature
        method: delete
        cors: true
        private: true

emailVerification:
  handler: gatways/subscriber/main.emailVerification
  events:
    - http:
        path: /subscriber/emailverification/{email}
        method: get
        cors: true
        private: true
checkAccountExists:
  handler: gatways/subscriber/main.checkAccountExists
  events:
    - http:
        path: /subscriber/account
        method: post
        cors: true
        private: true
updateBillingCard:
  handler: gatways/subscriber/main.updateBillingCard
  events:
    - http:
        path: /subscriber/card
        method: patch
        cors: true
        private: true

updateBillingDate:
  handler: gatways/subscriber/main.updateBillingDate
  events:
    - http:
        path: /signature/date
        method: put
        cors: true
        private: true
getCardsByCustomer:
  handler: gatways/subscriber/main.getCardsByCustomer
  events:
    - http:
        path: /signature/cards
        method: get
        cors: true
        private: true
